/* Common-word list (roughly frequency-ordered) for glide-typing decode.
 * A swipe is scored against words that are a subsequence of the keys crossed,
 * anchored on at least one endpoint and preferring longer / more common words. */
window.WORDS = [
  "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at",
  "this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would",
  "there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can",
  "like","time","no","just","him","know","take","people","into","year","your","good","some","could","them",
  "see","other","than","then","now","look","only","come","its","over","think","also","back","after","use",
  "two","how","our","work","first","well","way","even","new","want","because","any","these","give","day",
  "most","us","is","are","was","were","been","has","had","said","each","does","did","going","got","made",
  "many","much","such","here","where","why","how","again","great","little","own","under","last","never",
  "us","left","right","old","high","every","big","small","next","few","while","might","must","should","need",
  "really","around","something","nothing","someone","everyone","anything","together","different","important",
  "hello","hi","hey","yes","no","okay","sure","thanks","thank","please","sorry","welcome","bye","later",
  "today","tomorrow","yesterday","morning","night","evening","week","month","weekend","tonight","soon",
  "world","home","house","room","door","water","food","coffee","tea","lunch","dinner","breakfast","money",
  "phone","call","message","text","email","photo","picture","video","music","song","play","pause","stop",
  "book","read","write","word","letter","note","page","story","news","idea","question","answer","problem",
  "meet","meeting","talk","chat","ask","tell","show","send","share","reply","open","close","start","end",
  "walk","run","drive","travel","trip","car","train","bus","road","street","city","place","world","country",
  "friend","family","people","person","child","kid","man","woman","name","love","help","care","feel","feeling",
  "happy","sad","tired","hungry","busy","free","ready","late","early","fast","slow","easy","hard","nice","cool",
  "learn","study","school","class","teacher","student","work","job","office","team","company","project","plan",
  "meta","glasses","camera","keyboard","screen","display","button","menu","search","google","assistant","brain",
  "neural","band","gesture","touch","swipe","tap","hold","press","select","scroll","zoom","view","mode","voice",
  "look","find","check","update","change","move","turn","set","keep","let","put","bring","leave","stay","wait",
  "come","went","seen","done","made","take","took","give","gave","find","found","tell","told","feel","felt",
  "buy","sell","pay","cost","price","order","book","cook","clean","wash","fix","build","design","create","make",
  "morning","light","dark","warm","cold","hot","rain","sun","cloud","wind","snow","weather","spring","summer",
  "black","white","blue","green","red","yellow","color","bright","dark","light","clear","open","full","empty",
];
